### ISSUE TITLE
Issues about the cfDNA result

### ISSUE THREAD

**Issue by jsonProgram** [niu-lab/msisensor2#12]
hello Dr.Niu,
I had test MSIsensor2 for cfDNA sample.

There is some issues confused me.

At First I try the Tumor-Only  for the cfDNA sample:

<<# CODE START
bin/msisensor2/msisensor2 msi \
-d hg19.list \
-t cfDNA.bam \
-o output/Tumor-Only \
<<# CODE END
## hg19.list : bin/msisensor2/msisensor2 scan hg19.fa -l 7 -o ./hg19.list

<<# Result
Total_Number_of_Sites   Number_of_Somatic_Sites %
cfDNA-sample-1    2456   219   8.92

And then I get the PBMC sample for this cfDNA from the same blood tube.
<<# CODE START
bin/msisensor2/msisensor2 msi \
-d hg19.list \
-n PBMC.bam \
-t cfDNA.bam \
-o output/Tumor-Only \
<<# CODE END

<<# Result
Total_Number_of_Sites   Number_of_Somatic_Sites %
**cfDNA-sample-1    2275   495   21.7**

This result is confused me.
Any suggestion?

ps:PBMC and cfDNA uses the WES Panel and NGS sequencing.

Json

**Comment by owehann** [comment]
Hi Json
For tumor only method , -M paramter must be specified, and I think, the models_hg19_GRch37 is suitable for your bam.
Actually, we have a beta version with advanced algorithm which has already shown its powerful classification ability on our cfDNA samples. Leave your email and we can offer it to you. Simultaneously, as the first users trying our new method, we hope you can provide detailed information about your cfDNA samples and final results. Besides，if your are willing to provide your samples, we can have a more in-depth cooperation.
Thanks 
Xinyin

**Comment by jsonProgram** [comment]
Hi Xinyin,
my e-mail: jsonyfp@gmail.com.

Thanks!
Json

**Comment by jsonProgram** [comment]
Thank for your Help!

Json
