### ISSUE TITLE
We have downloaded two version software in November 2019 and 2020 respectively.However,the results of tumor only from these two versions were inconsistent.Is it normal?

### ISSUE THREAD

**Issue by biofer** [niu-lab/msisensor2#17]
The first version: Software downloaded on November 12, 2019
**Result**
```
loading bed regions ...
loading homopolymer and microsatellite sites ...
Total loading windows:  61 
Total loading homopolymer and microsatellites:  71 
......
......
......
*** Summary information ***

Number of total sites: 71
Number of sites with enough coverage: 68
Number of MSI sites: 1
MSI score(%): 1.47059

Total time consumed:  11 secs
```
The second version: Software downloaded on August 28, 2020
**Result**
```
loading bed regions ...
loading homopolymer and microsatellite sites ...
Total loading windows:  61 
Total loading homopolymer and microsatellites:  71 
......
......
......
*** Summary information ***

Number of total sites: 71
Number of sites with enough coverage: 0
Number of MSI sites: 0
MSI score(%): 0

Total time consumed:  3 secs
```
The results from these two versions were inconsistent. No site was covered from the second version. Is it normal?

additional information：
**The pair sample Result**
```
loading bed regions ...
loading homopolymer and microsatellite sites ...
Total loading windows:  285 
Total loading homopolymer and microsatellites:  844 
*** Summary information ***

Number of total sites: 844
Number of sites with enough coverage: 709
Number of MSI sites: 45
MSI score(%): 6.34697

Total time consumed:  188 secs
```

**Comment by af8** [comment]
Hi,
Did you find an answer for this ?
Anthony

**Comment by ZhaoDanOnGitHub** [comment]
您好，您的邮件已收到！

**Comment by ArsFc** [comment]
> The first version: Software downloaded on November 12, 2019 **Result**
> 
> ```
> loading bed regions ...
> loading homopolymer and microsatellite sites ...
> Total loading windows:  61 
> Total loading homopolymer and microsatellites:  71 
> ......
> ......
> ......
> *** Summary information ***
> 
> Number of total sites: 71
> Number of sites with enough coverage: 68
> Number of MSI sites: 1
> MSI score(%): 1.47059
> 
> Total time consumed:  11 secs
> ```
> 
> The second version: Software downloaded on August 28, 2020 **Result**
> 
> ```
> loading bed regions ...
> loading homopolymer and microsatellite sites ...
> Total loading windows:  61 
> Total loading homopolymer and microsatellites:  71 
> ......
> ......
> ......
> *** Summary information ***
> 
> Number of total sites: 71
> Number of sites with enough coverage: 0
> Number of MSI sites: 0
> MSI score(%): 0
> 
> Total time consumed:  3 secs
> ```
> 
> The results from these two versions were inconsistent. No site was covered from the second version. Is it normal?
> 
> additional information： **The pair sample Result**
> 
> ```
> loading bed regions ...
> loading homopolymer and microsatellite sites ...
> Total loading windows:  285 
> Total loading homopolymer and microsatellites:  844 
> *** Summary information ***
> 
> Number of total sites: 844
> Number of sites with enough coverage: 709
> Number of MSI sites: 45
> MSI score(%): 6.34697
> 
> Total time consumed:  188 secs
> ```

 Can supp The first version downloaded Software on  2019 ,thanks！！！

**Comment by ZhaoDanOnGitHub** [comment]
您好，您的邮件已收到！
