### ISSUE TITLE
-d msisensor2_scan_result vs -M Model ?

### ISSUE THREAD

**Issue by gudeqing** [niu-lab/msisensor2#18]
Hi, I found that options '-d' and '-M' could be either used, and the value of '-d' is the result of 'scan' while the value of '-M' is a predefined model. These two options will lead to different 'Number of total sites: ?',  thus I wonder to know which one is prefered for tumor only mode.
With best regards!

**Comment by owehann** [comment]
'-M' is a more suitable option. '-d' is a parameter inherited from MSIsensor to ensure that MSIsensor2 can still implement msIsensor's functionality, which is MSI detection for tumor-normal paired samples.
