### ISSUE TITLE
Permissions issue?

### ISSUE THREAD

**Issue by MikeWLloyd** [niu-lab/msisensor2#2]
I am working to implement your tool on a compute cluster. I am having an issue, and I wonder if you could provide input. 

When I run with local files: 
```
/home/lloydm/msisensor2/msisensor2 msi -M /home/lloydm/msisensor2/models_hg38 -d /home/lloydm/msisensor2/hg38_microsat.list -t <INPUTBAM> -o <OUTPUT> 
```

The tool provides valid output:
```
Number of total sites: 1861116
Number of sites with enough coverage: 58
Number of MSI sites: 1
MSI score(%): 1.72414
```

When a different user tries to run the same command with the same inputs, the tool returns this output with no other apparent differences in the output log.

```
Number of total sites: 1861116
Number of sites with enough coverage: 0
Number of MSI sites: 0
MSI score(%): 0
```

I can only assume there are permissions issues involved here, but in my view, the tool should not produce output with zeros, if it failed to write to a location or load a particular file needed.

**Comment by Beifang** [comment]
Hi, -d option is not required in msisensor2. So, just run: 
/home/lloydm/msisensor2/msisensor2 msi -M /home/lloydm/msisensor2/models_hg38 -t <INPUTBAM> -o <OUTPUT> 

I will update readme soon.

**Comment by MikeWLloyd** [comment]
Will running with -d affect the final metrics? Can you expand on why it is not required? 

Also, running without the -d flag as you suggest did not fix the issue. Values still return as zeros. When the user copies the models directory to their local directory, and runs the tool, the run finishes with expected values.

**Comment by owehann** [comment]
Owing to the machine learning method, the distinguishing sites are selected, so the -d parameter is no longer needed to specify the bed file.

If  the expected results can be obtained by changing the directory.
Then you need to verify：
 1. In the original command, the file's directory specified by -M is correct.
 2. The user has the permission of the folder under original address.

**Comment by biofer** [comment]
> Will running with -d affect the final metrics? Can you expand on why it is not required?
> 
> Also, running without the -d flag as you suggest did not fix the issue. Values still return as zeros. When the user copies the models directory to their local directory, and runs the tool, the run finishes with expected values.

Yes,  I have the same problem. 
I set the write permissions to folders for other users and it work. I think it's dangerous if someone  changed the files。
