### ISSUE TITLE
How many Microsatellites (MS) included in a customized panel is accurate when analyzed by msisensor2?  

### ISSUE THREAD

**Issue by biofer** [niu-lab/msisensor2#27]
Dear author,

How many Microsatellites (MS) included in a customized panel is accurate when analyzed by msisensor2?  

Thank you very much for your work！

**Comment by ZhaoDanOnGitHub** [comment]
您好，您的邮件已收到！

**Comment by Beifang** [comment]
It's hard to say how many MSs is accurate for msisensor2.  We actually test that on TCGA WES samples, and we can get almost 100% AUC using only 10 random sites. As for a customized panel, I think a validation is needed for accurate cutoff.

**Comment by biofer** [comment]
Thank you for your reply! We will verify the cutoff of our customized panel based on our clinical samples.
