### ISSUE TITLE
Clarification on -c option

### ISSUE THREAD

**Issue by KDasu-OneCell** [niu-lab/msisensor2#50]
Hi,

Could you clarify what measure of coverage the -c option for the msi command represents? Is it coverage depth (in reads) or width (in base pairs)?

**Comment by ZhaoDanOnGitHub** [comment]
您好，您的邮件已收到！

**Comment by Beifang** [comment]
You can understand it as depth, which is actually the total read count covering each ms site. For example, consider the following site:

chr1 25256278 ATCTT 5[GCC] GCAGG
N: 0 0 0 16 279 1 0 0 0 0 
T: 0 0 2 27 666 0 0 0 0 0 

In the normal sample, the depth is calculated as 16+279+1=296, and in the tumor sample, the depth is 2+27+666=695.
